name: 'Pester'
description: 'Pester'
inputs:
  script:  # id of input
    description: 'What to test'
    required: true
    default: './'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: node12
  main: _init/index.js
